name: Daily Cypress Tests

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Chrome and Xvfb
        run: xvfb-run npx cypress run --browser chrome

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots